//! Article 50 transparency primitive -- HTML snippet renderer.
//!
//! Article 50 of the EU AI Act requires natural persons interacting
//! with an AI system to be informed of that fact. The deployer
//! mounts the snippet returned by [`transparency_banner`] above (or
//! within) any AI surface that converses, generates content, or
//! classifies emotions / biometrics.

use serde::{Deserialize, Serialize};

/// Context fed to [`transparency_banner`]. Drives the wording of
/// the disclosure: a chatbot says different things than an emotion-
/// recognition system.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TransparencyContext {
    /// Short name of the AI system, surfaced inside the banner so
    /// the user knows which model they're interacting with.
    pub system_name: String,
    /// Article-50 category. Drives the disclosure wording.
    pub category: TransparencyCategory,
    /// Optional URL to the model card. Renders as a "Learn more"
    /// link inside the banner.
    pub model_card_url: Option<String>,
    /// Optional support / opt-out URL. Article 50(3) requires
    /// users be able to refuse the interaction; this is where
    /// they go.
    pub opt_out_url: Option<String>,
}

/// Which Article 50 category drives the disclosure copy.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum TransparencyCategory {
    /// Conversational AI -- chatbot, agent. The deployer tells
    /// users they are interacting with a machine. (Article 50(1))
    Chatbot,
    /// Emotion recognition system. The deployer tells users their
    /// emotional state is being inferred. (Article 50(3))
    EmotionRecognition,
    /// Biometric categorisation system. The deployer tells users
    /// their biometric features are being classified. (Article 50(3))
    BiometricCategorisation,
    /// Generated / manipulated content (synthetic media, deepfakes).
    /// Output must be machine-readable as AI-generated.
    /// (Article 50(2) / Article 50(4))
    SyntheticContent,
}

impl TransparencyCategory {
    /// One-line disclosure text rendered inside the banner.
    #[must_use]
    pub fn disclosure(&self) -> &'static str {
        match self {
            TransparencyCategory::Chatbot =>
                "You are interacting with an AI system, not a human. Responses are generated by a machine.",
            TransparencyCategory::EmotionRecognition =>
                "This system infers your emotional state from inputs (text / voice / facial expression). You may decline this interaction.",
            TransparencyCategory::BiometricCategorisation =>
                "This system classifies you using biometric features. You may decline this interaction.",
            TransparencyCategory::SyntheticContent =>
                "The following content was generated or substantially manipulated by an AI system.",
        }
    }

    /// Slug for use in URLs / log fields. Stable.
    #[must_use]
    pub fn slug(&self) -> &'static str {
        match self {
            TransparencyCategory::Chatbot => "chatbot",
            TransparencyCategory::EmotionRecognition => "emotion-recognition",
            TransparencyCategory::BiometricCategorisation => "biometric-categorisation",
            TransparencyCategory::SyntheticContent => "synthetic-content",
        }
    }
}

/// Render a self-contained HTML snippet implementing Article 50
/// transparency. The deployer drops the returned string at the top
/// of any AI surface they expose to natural persons; CSS is inline
/// so the banner works whether or not the host page imports the
/// Computeza stylesheet.
#[must_use]
pub fn transparency_banner(ctx: &TransparencyContext) -> String {
    let disclosure = ctx.category.disclosure();
    let mut links = String::new();
    if let Some(card) = ctx.model_card_url.as_deref() {
        links.push_str(&format!(
            r#" <a href="{}" style="color: inherit; text-decoration: underline;">Model card</a>"#,
            html_escape(card)
        ));
    }
    if let Some(opt) = ctx.opt_out_url.as_deref() {
        links.push_str(&format!(
            r#" <a href="{}" style="color: inherit; text-decoration: underline; margin-left: 0.6rem;">Decline this interaction</a>"#,
            html_escape(opt)
        ));
    }
    format!(
        r#"<aside role="note" aria-label="AI system disclosure" data-cz-transparency="{slug}" style="border: 1px solid rgba(245, 181, 68, 0.55); background: rgba(245, 181, 68, 0.06); padding: 0.65rem 0.85rem; border-radius: 0.4rem; font-size: 0.86rem; line-height: 1.45;">
<strong>{name}</strong> &mdash; {disclosure}{links}
</aside>"#,
        slug = ctx.category.slug(),
        name = html_escape(&ctx.system_name),
        disclosure = html_escape(disclosure),
        links = links,
    )
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn transparency_banner_renders_disclosure_and_name() {
        let html = transparency_banner(&TransparencyContext {
            system_name: "AgentDesk".into(),
            category: TransparencyCategory::Chatbot,
            model_card_url: None,
            opt_out_url: None,
        });
        assert!(html.contains("AgentDesk"));
        assert!(html.contains("interacting with an AI system"));
        assert!(html.contains(r#"data-cz-transparency="chatbot""#));
    }

    #[test]
    fn transparency_banner_emits_model_card_and_opt_out_links_when_present() {
        let html = transparency_banner(&TransparencyContext {
            system_name: "BioGate".into(),
            category: TransparencyCategory::BiometricCategorisation,
            model_card_url: Some("/compliance/models/biogate".into()),
            opt_out_url: Some("https://help.example/decline".into()),
        });
        assert!(html.contains("/compliance/models/biogate"));
        assert!(html.contains("Decline this interaction"));
    }

    #[test]
    fn transparency_banner_escapes_html_in_system_name() {
        let html = transparency_banner(&TransparencyContext {
            system_name: "<script>alert(1)</script>".into(),
            category: TransparencyCategory::Chatbot,
            model_card_url: None,
            opt_out_url: None,
        });
        assert!(!html.contains("<script>"));
        assert!(html.contains("&lt;script&gt;"));
    }

    #[test]
    fn transparency_category_disclosures_are_distinct_per_category() {
        let chat = TransparencyCategory::Chatbot.disclosure();
        let emo = TransparencyCategory::EmotionRecognition.disclosure();
        let bio = TransparencyCategory::BiometricCategorisation.disclosure();
        let syn = TransparencyCategory::SyntheticContent.disclosure();
        // Pairwise distinct.
        let xs = [chat, emo, bio, syn];
        for i in 0..xs.len() {
            for j in (i + 1)..xs.len() {
                assert_ne!(xs[i], xs[j]);
            }
        }
    }
}
